#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

echo "🚀 Welcome to the jvegaf/dotfiles installer!"
echo "-------------------------------------------------"
echo
read -rp "🤔  Where do you want to clone the dotfiles? (default ~/.dotfiles): " DOTFILES_PATH
echo

echo "Installing previuos dependencies"
sudo apt update && sudo apt install -y fzf rustc cargo
#sudo pacman -S rust fzf
chsh -s `which zsh`
cargo install exa docpars delta
export PATH="$HOME/.cargo/bin:$PATH"

export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

git clone --recurse-submodules -j8 --depth 1 https://github.com/jvegaf/dotfiles.git "$DOTFILES_PATH"

"$DOTFILES_PATH/bin/dot" self install
