#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/symlinks_tool.sh"

##? Add intellij Configurations symlink (since it's not synced via JetBrains Toolbox)
#?? 1.0.0
##?
##? Usage:
##?   set_config
docs::eval "$@"

log::note "Applying Intellij Symlinks"
apply_intellij_symlinks
