#!/usr/bin/env bash
ZIM_HOME=${ZDOTDIR:-${HOME}}/.dotfiles/modules/zimfw

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/install.sh"

if platform::is_macos; then
  log::note "Installing MacOS  custom packages"

  install_macos_custom
fi

if platform::is_linux; then
  log::note "Installing Linux 🐧 custom packages"

  install_linux_custom
fi

log::note "Installing python packages"
pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt" || true
pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt"

#log::note "Installing php packages"
#composer global install

#log::note "Installing npm packages"
#xargs sudo npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

log::note "Setting ZSH as the default shell"
chsh -s "$(command -v zsh)"

#read -rp "🦑 Git config: What is you email? " git_email
#read -rp "🐙 Git config: And your name? " git_name

#git config --global user.email "$git_email"
#git config --global user.name "$git_name"
source "$DOTFILES_PATH/shell/zsh/.zshenv"
source "$DOTFILES_PATH/modules/zimfw/zimfw.zsh" install

"$DOTFILES_PATH/bin/dot" self update

