#!/usr/bin/env bash
source "$DOTFILES_PATH/scripts/core/_main.sh"
source "$DOTFILES_PATH/scripts/self/utils/symlinks_tool.sh"

set -euo pipefail

##? Install the dotfiles
#?? 1.0.0
##?
##? Usage:
##?   install

docs::eval "$@"

if platform::is_macos; then
  log::note "Installing MacOS  custom packages"

  install_macos_custom
fi

if platform::is_linux; then
  log::note "Installing Linux 🐧 custom packages"

  install_linux_custom
fi

#log::note "Installing python packages"
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt" || true
#pip3 install -r "$DOTFILES_PATH/langs/python/requirements.txt"

#log::note "Installing php packages"
#composer global install

#log::note "Installing npm packages"
#xargs sudo npm install -g <"$DOTFILES_PATH/langs/js/global_modules.txt"

log::note "Applying common Symlinks "
apply_common_symlinks

log::note "Applying Linux Symlinks"
apply_linux_symlinks

log::note "Setting ZSH as the default shell"
sudo usermod -s "$(which zsh)"
# chsh -s "$(command -v zsh)"

source "$DOTFILES_PATH/shell/zsh/.zshenv"

"$DOTFILES_PATH/bin/dot" self update

